### ISSUE TITLE
Set code blocks to full width

### ISSUE THREAD

**Issue by dvz** [mybb/mybb-website-theme#7]
Code blocks currently have variable width and may overflow: https://docs.mybb.com/1.8/administration/security/https/

**Comment by justinsoltesz** [comment]
Code blocks now have a maximum width and will break lines if necessary. I've pushed commits to the mybb.com and docs.mybb.com repositories so they will update.

**Comment by dvz** [comment]
Code block content should now wrap instead of overflowing in `.wrapper`, and should wrap in relation to the table of contents (which was problematic on pages like https://docs.mybb.com/1.8/development/plugins/database-methods/) once the cached CSS expires. `pre` elements are still rendered under `.toc` though (resulting in the gray background being cut), so it might be better if e.g. the listing is hidden by default or takes 100% width on top so we don't have to deal with `float` side effects.
